spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
      datasource:
        ds1.nacos.server-addr: localhost:8848
        ds1.nacos.data-id: sentinel-degrade-rule
        ds1.nacos.rule-type: degrade
server:
  port: 22222

feign:
  sentinel:
    enabled: true
